// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: types.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxPropagationConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TraderApis            []string               `protobuf:"bytes,1,rep,name=trader_apis,json=traderApis,proto3" json:"trader_apis,omitempty"`
	TxForwarders          []*TxForwarder         `protobuf:"bytes,2,rep,name=tx_forwarders,json=txForwarders,proto3" json:"tx_forwarders,omitempty"`
	NumTraderApisParallel uint32                 `protobuf:"varint,3,opt,name=num_trader_apis_parallel,json=numTraderApisParallel,proto3" json:"num_trader_apis_parallel,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TxPropagationConfig) Reset() {
	*x = TxPropagationConfig{}
	mi := &file_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxPropagationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxPropagationConfig) ProtoMessage() {}

func (x *TxPropagationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxPropagationConfig.ProtoReflect.Descriptor instead.
func (*TxPropagationConfig) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *TxPropagationConfig) GetTraderApis() []string {
	if x != nil {
		return x.TraderApis
	}
	return nil
}

func (x *TxPropagationConfig) GetTxForwarders() []*TxForwarder {
	if x != nil {
		return x.TxForwarders
	}
	return nil
}

func (x *TxPropagationConfig) GetNumTraderApisParallel() uint32 {
	if x != nil {
		return x.NumTraderApisParallel
	}
	return 0
}

type TxForwarder struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Addr               string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	SupportedProtocols []string               `protobuf:"bytes,2,rep,name=supported_protocols,json=supportedProtocols,proto3" json:"supported_protocols,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TxForwarder) Reset() {
	*x = TxForwarder{}
	mi := &file_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxForwarder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxForwarder) ProtoMessage() {}

func (x *TxForwarder) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxForwarder.ProtoReflect.Descriptor instead.
func (*TxForwarder) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

func (x *TxForwarder) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *TxForwarder) GetSupportedProtocols() []string {
	if x != nil {
		return x.SupportedProtocols
	}
	return nil
}

var File_types_proto protoreflect.FileDescriptor

const file_types_proto_rawDesc = "" +
	"\n" +
	"\vtypes.proto\x12\x05types\"\xa8\x01\n" +
	"\x13TxPropagationConfig\x12\x1f\n" +
	"\vtrader_apis\x18\x01 \x03(\tR\n" +
	"traderApis\x127\n" +
	"\rtx_forwarders\x18\x02 \x03(\v2\x12.types.TxForwarderR\ftxForwarders\x127\n" +
	"\x18num_trader_apis_parallel\x18\x03 \x01(\rR\x15numTraderApisParallel\"R\n" +
	"\vTxForwarder\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12/\n" +
	"\x13supported_protocols\x18\x02 \x03(\tR\x12supportedProtocolsB7Z5github.com/bloXroute-Labs/solana-gateway/pkg/protobufb\x06proto3"

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData []byte
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)))
	})
	return file_types_proto_rawDescData
}

var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_types_proto_goTypes = []any{
	(*TxPropagationConfig)(nil), // 0: types.TxPropagationConfig
	(*TxForwarder)(nil),         // 1: types.TxForwarder
}
var file_types_proto_depIdxs = []int32{
	1, // 0: types.TxPropagationConfig.tx_forwarders:type_name -> types.TxForwarder
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
